import { Button, TextEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component CalculatorView inherits Window {
    callback inputDigit(int);
    callback inputOperation(string);
    callback clear();
    callback erase();
    callback inputEquals();
    in-out property<string> display;

    width: 400px;
    height: 500px;
    background: #f0f0f0;

    // Display
    VerticalBox {
      padding: 10px;
      spacing: 5px;
      //alignment: stretch;
      //vertical-stretch: 1.0;
      //horizontal-stretch: 1.0;

      display_text := TextEdit {
          text: root.display;
          wrap: no-wrap;
          read-only: true;
          font-size: 32px;
          horizontal-alignment: right;
      }

      GridLayout {
          spacing: 5px;
          vertical-stretch: 1.0;
          horizontal-stretch: 1.0;

          // Row 0: Clear and Eraser spanning two columns each
          Row {
            Button { text: "%"; clicked => { root.inputOperation("%"); display_text.text = root.display }; }
            Button { text: "C"; clicked => { root.clear(); display_text.text = root.display }; }
            Button { colspan: 2; text: "←"; clicked => { root.erase(); display_text.text = root.display }; }
          }

          // Row 1: 7 8 9 /
          Row {
            Button { text: "7"; clicked => { root.inputDigit(7); display_text.text = root.display }; }
            Button { text: "8"; clicked => { root.inputDigit(8); display_text.text = root.display }; }
            Button { text: "9"; clicked => { root.inputDigit(9); display_text.text = root.display }; }
            Button { text: "/"; clicked => { root.inputOperation("/"); display_text.text = root.display }; }
          }

          // Row 2: 4 5 6 *
          Row {
            Button { text: "4"; clicked => { root.inputDigit(4); display_text.text = root.display }; }
            Button { text: "5"; clicked => { root.inputDigit(5); display_text.text = root.display }; }
            Button { text: "6"; clicked => { root.inputDigit(6); display_text.text = root.display }; }
            Button { text: "*"; clicked => { root.inputOperation("*"); display_text.text = root.display }; }
          }

          // Row 3: 1 2 3 -
          Row {
            Button { text: "1"; clicked => { root.inputDigit(1); display_text.text = root.display }; }
            Button { text: "2"; clicked => { root.inputDigit(2); display_text.text = root.display }; }
            Button { text: "3"; clicked => { root.inputDigit(3); display_text.text = root.display }; }
            Button { text: "-"; clicked => { root.inputOperation("-"); display_text.text = root.display }; }
          }

          // Row 4: 0 % = +
          Row {
            Button { colspan: 2; text: "0"; clicked => { root.inputDigit(0); display_text.text = root.display }; }
            Button { text: "="; clicked => { root.inputEquals(); display_text.text = root.display }; }
            Button { text: "+"; clicked => { root.inputOperation("+"); display_text.text = root.display }; }
          }
      }
    }
}
